// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { KeyValue, KeyValueT } from '../reflection/KeyValue.js';
import { Object_, Object_T } from '../reflection/Object.js';


export class RPCCall implements flatbuffers.IUnpackableObject<RPCCallT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RPCCall {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRPCCall(bb:flatbuffers.ByteBuffer, obj?:RPCCall):RPCCall {
  return (obj || new RPCCall()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRPCCall(bb:flatbuffers.ByteBuffer, obj?:RPCCall):RPCCall {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RPCCall()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

request(obj?:Object_):Object_|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Object_()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

response(obj?:Object_):Object_|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Object_()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

attributes(index: number, obj?:KeyValue):KeyValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new KeyValue()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

attributes_Length():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

documentation(index: number):string
documentation(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
documentation(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

documentation_Length():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName():string {
  return 'reflection.RPCCall';
}

static startRPCCall(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static add_name(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static add_request(builder:flatbuffers.Builder, requestOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, requestOffset, 0);
}

static add_response(builder:flatbuffers.Builder, responseOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, responseOffset, 0);
}

static add_attributes(builder:flatbuffers.Builder, attributesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, attributesOffset, 0);
}

static create_attributes_Vector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static start_attributes_Vector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static add_documentation(builder:flatbuffers.Builder, documentationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, documentationOffset, 0);
}

static create_documentation_Vector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static start_documentation_Vector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endRPCCall(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // name
  builder.requiredField(offset, 6) // request
  builder.requiredField(offset, 8) // response
  return offset;
}


unpack(): RPCCallT {
  return new RPCCallT(
    this.name(),
    (this.request() !== null ? this.request()!.unpack() : null),
    (this.response() !== null ? this.response()!.unpack() : null),
    this.bb!.createObjList<KeyValue, KeyValueT>(this.attributes.bind(this), this.attributes_Length()),
    this.bb!.createScalarList<string>(this.documentation.bind(this), this.documentation_Length())
  );
}


unpackTo(_o: RPCCallT): void {
  _o.name = this.name();
  _o.request = (this.request() !== null ? this.request()!.unpack() : null);
  _o.response = (this.response() !== null ? this.response()!.unpack() : null);
  _o.attributes = this.bb!.createObjList<KeyValue, KeyValueT>(this.attributes.bind(this), this.attributes_Length());
  _o.documentation = this.bb!.createScalarList<string>(this.documentation.bind(this), this.documentation_Length());
}
}

export class RPCCallT implements flatbuffers.IGeneratedObject {
constructor(
  public name: string|Uint8Array|null = null,
  public request: Object_T|null = null,
  public response: Object_T|null = null,
  public attributes: (KeyValueT)[] = [],
  public documentation: (string)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const request = (this.request !== null ? this.request!.pack(builder) : 0);
  const response = (this.response !== null ? this.response!.pack(builder) : 0);
  const attributes = RPCCall.create_attributes_Vector(builder, builder.createObjectOffsetList(this.attributes));
  const documentation = RPCCall.create_documentation_Vector(builder, builder.createObjectOffsetList(this.documentation));

  RPCCall.startRPCCall(builder);
  RPCCall.add_name(builder, name);
  RPCCall.add_request(builder, request);
  RPCCall.add_response(builder, response);
  RPCCall.add_attributes(builder, attributes);
  RPCCall.add_documentation(builder, documentation);

  return RPCCall.endRPCCall(builder);
}
}
