// automatically generated by the FlatBuffers compiler, do not modify

package Testing.KeySearch;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FloatEntry extends Table {
  public static FloatEntry getRootAsFloatEntry(ByteBuffer _bb) { return getRootAsFloatEntry(_bb, new FloatEntry()); }
  public static FloatEntry getRootAsFloatEntry(ByteBuffer _bb, FloatEntry obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public FloatEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float key() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public boolean mutateKey(float key) { int o = __offset(4); if (o != 0) { bb.putFloat(o + bb_pos, key); return true; } else { return false; } }
  public float value() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 1234.0f; }
  public boolean mutateValue(float value) { int o = __offset(6); if (o != 0) { bb.putFloat(o + bb_pos, value); return true; } else { return false; } }

  public static int createFloatEntry(FlatBufferBuilder builder,
      float key,
      float value) {
    builder.startObject(2);
    FloatEntry.addValue(builder, value);
    FloatEntry.addKey(builder, key);
    return FloatEntry.endFloatEntry(builder);
  }

  public static void startFloatEntry(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addKey(FlatBufferBuilder builder, float key) { builder.addFloat(0, key, 0.0f); }
  public static void addValue(FlatBufferBuilder builder, float value) { builder.addFloat(1, value, 1234.0f); }
  public static int endFloatEntry(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }

  @Override
  protected int keysCompare(Integer o1, Integer o2, ByteBuffer _bb) {
    float val_1 = _bb.getFloat(o1+__offset(4, o1, _bb));
    float val_2 = _bb.getFloat(o2+__offset(4, o2, _bb));
    return val_1 > val_2 ? 1 : val_1 < val_2 ? -1 : 0;
  }

  public static int lookupByKey( int bb_pos, int fieldDataOffset, float key, float defaultKeyValue , ByteBuffer bb) {
    if ( fieldDataOffset == 0 )
        return 0;
    int vectorOffsetPos = bb_pos + fieldDataOffset;
    int vectorLocation = bb.getInt( vectorOffsetPos ) + vectorOffsetPos;
    int span = bb.getInt(vectorLocation);
    vectorLocation += 4;
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = __indirect(vectorLocation + 4 * (start + middle), bb);
      int keyValueOffset = __offset( 4, tableOffset, bb );
      float val = keyValueOffset != 0 ? bb.getFloat(tableOffset + keyValueOffset) : defaultKeyValue;
      if (key < val) {
        span = middle;
      } else if (key > val) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return tableOffset;
      }
    }
    return 0;
  }
}

