// automatically generated by the FlatBuffers compiler, do not modify

package KeySearch

const (
	FruitFilterApple = 1
	FruitFilterApricot = 2
	FruitFilterAvocado = 4
	FruitFilterBanana = 8
	FruitFilterBilberry = 16
	FruitFilterBlackberry = 32
	FruitFilterBlackcurrant = 64
	FruitFilterBlueberry = 128
	FruitFilterBoysenberry = 256
	FruitFilterCurrant = 512
	FruitFilterCherry = 1024
	FruitFilterCherimoya = 2048
	FruitFilterCloudberry = 4096
	FruitFilterCoconut = 8192
	FruitFilterCranberry = 16384
	FruitFilterDamson = 32768
	FruitFilterDate = 65536
	FruitFilterDragonfruit = 131072
	FruitFilterDurian = 262144
	FruitFilterElderberry = 524288
	FruitFilterFeijoa = 1048576
	FruitFilterFig = 2097152
	FruitFilterGojiberry = 4194304
	FruitFilterGooseberry = 8388608
	FruitFilterGrape = 16777216
	FruitFilterRaisin = 33554432
	FruitFilterGrapefruit = 67108864
	FruitFilterGuava = 134217728
)

var EnumNamesFruitFilter = map[int]string{
	FruitFilterApple:"Apple",
	FruitFilterApricot:"Apricot",
	FruitFilterAvocado:"Avocado",
	FruitFilterBanana:"Banana",
	FruitFilterBilberry:"Bilberry",
	FruitFilterBlackberry:"Blackberry",
	FruitFilterBlackcurrant:"Blackcurrant",
	FruitFilterBlueberry:"Blueberry",
	FruitFilterBoysenberry:"Boysenberry",
	FruitFilterCurrant:"Currant",
	FruitFilterCherry:"Cherry",
	FruitFilterCherimoya:"Cherimoya",
	FruitFilterCloudberry:"Cloudberry",
	FruitFilterCoconut:"Coconut",
	FruitFilterCranberry:"Cranberry",
	FruitFilterDamson:"Damson",
	FruitFilterDate:"Date",
	FruitFilterDragonfruit:"Dragonfruit",
	FruitFilterDurian:"Durian",
	FruitFilterElderberry:"Elderberry",
	FruitFilterFeijoa:"Feijoa",
	FruitFilterFig:"Fig",
	FruitFilterGojiberry:"Gojiberry",
	FruitFilterGooseberry:"Gooseberry",
	FruitFilterGrape:"Grape",
	FruitFilterRaisin:"Raisin",
	FruitFilterGrapefruit:"Grapefruit",
	FruitFilterGuava:"Guava",
}

