// automatically generated by the FlatBuffers compiler, do not modify

namespace Testing.KeySearch
{

using System;
using FlatBuffers;

public struct IntEntry : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static IntEntry GetRootAsIntEntry(ByteBuffer _bb) { return GetRootAsIntEntry(_bb, new IntEntry()); }
  public static IntEntry GetRootAsIntEntry(ByteBuffer _bb, IntEntry obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public IntEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Key { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)-2147483648; } }
  public bool MutateKey(int key) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, key); return true; } else { return false; } }
  public int Value { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)-2147483648; } }
  public bool MutateValue(int value) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, value); return true; } else { return false; } }

  public static Offset<IntEntry> CreateIntEntry(FlatBufferBuilder builder,
      int key = -2147483648,
      int value = -2147483648) {
    builder.StartObject(2);
    IntEntry.AddValue(builder, value);
    IntEntry.AddKey(builder, key);
    return IntEntry.EndIntEntry(builder);
  }

  public static void StartIntEntry(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddKey(FlatBufferBuilder builder, int key) { builder.AddInt(0, key, -2147483648); }
  public static void AddValue(FlatBufferBuilder builder, int value) { builder.AddInt(1, value, -2147483648); }
  public static Offset<IntEntry> EndIntEntry(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<IntEntry>(o);
  }

  public static VectorOffset CreateMySortedVectorOfTables(FlatBufferBuilder builder, Offset<IntEntry>[] offsets) {
    Array.Sort(offsets, (Offset<IntEntry> o1, Offset<IntEntry> o2) => builder.DataBufferp.bb.GetInt(Table.__offset(4, o1.Value, builder.DataBuffer)).CompareTo(builder.DataBufferp.bb.GetInt(Table.__offset(4, o2.Value, builder.DataBuffer))));
    return builder.CreateVectorOfTables(offsets);
  }

  public static IntEntry? LookupByKey(VectorOffset vectorOffset, int key, ByteBuffer bb) {
    int vectorLocation = bb.Length - vectorOffset.Value;
    int span = bb.GetInt(vectorLocation);
    int start = 0;
    vectorLocation += 4;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      int comp = __p.bb.GetInt(Table.__offset(4, bb.Length - tableOffset, bb)).CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return new IntEntry().__assign(tableOffset, bb);
      }
    }
    return null;
  }
};


}
