version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/rust/flatbuffers"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/rust/flexbuffers"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/kotlin"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/dart"
    schedule:
      interval: "weekly"
