# automatically generated by the FlatBuffers compiler, do not modify

UnionVector.eval(quote


FlatBuffers.@UNION(Character, (
    Nothing,
    Attacker,
    Rapunzel,
    BookReader,
    BookReader,
    String,
    String,
))


end)

