// automatically generated by the FlatBuffers compiler, do not modify

package NamespaceA

import com.google.flatbuffers.kotlin.*
@Suppress("unused")
class SecondTableInA : Table() {

    fun init(i: Int, buffer: ReadWriteBuffer) : SecondTableInA = reset(i, buffer)
    fun assign(i: Int, buffer: ReadWriteBuffer) : SecondTableInA = init(i, buffer)

    val referToC : NamespaceC.TableInC? get() = referToC(NamespaceC.TableInC())
    fun referToC(obj: NamespaceC.TableInC) : NamespaceC.TableInC? = lookupField(4, null ) { obj.assign(indirect(it + bufferPos), bb) }

    companion object {
        fun validateVersion() = VERSION_2_0_8

        fun asRoot(buffer: ReadWriteBuffer) : SecondTableInA = asRoot(buffer, SecondTableInA())
        fun asRoot(buffer: ReadWriteBuffer, obj: SecondTableInA) : SecondTableInA = obj.assign(buffer.getInt(buffer.limit) + buffer.limit, buffer)


        fun createSecondTableInA(builder: FlatBufferBuilder, referToCOffset: Offset<NamespaceC.TableInC>) : Offset<SecondTableInA> {
            builder.startTable(1)
            addReferToC(builder, referToCOffset)
            return endSecondTableInA(builder)
        }
        fun startSecondTableInA(builder: FlatBufferBuilder) = builder.startTable(1)

        fun addReferToC(builder: FlatBufferBuilder, referToC: Offset<NamespaceC.TableInC>) = builder.addOffset(0, referToC, null)

        fun endSecondTableInA(builder: FlatBufferBuilder) : Offset<SecondTableInA> {
            val o: Offset<SecondTableInA> = builder.endTable()
            return o
        }
    }
}
