// automatically generated by the FlatBuffers compiler, do not modify

package NamespaceA.NamespaceB;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class ColorTestTableT {
  private byte color;

  public byte getColor() { return color; }

  public void setColor(byte color) { this.color = color; }


  public ColorTestTableT() {
    this.color = 2;
  }
}

