// automatically generated by the FlatBuffers compiler, do not modify

package MyGame;

import com.moses.ofir;
import com.google.flatbuffers.FlatBufferBuilder;

@Ofir("union")
public class PointsUnion {
  private byte type;
  private Object value;

  public byte getType() { return type; }

  public void setType(byte type) { this.type = type; }

  public Object getValue() { return value; }

  public void setValue(Object value) { this.value = value; }

  public PointsUnion() {
    this.type = Points.NONE;
    this.value = null;
  }

  public MyGame.PointOneT asPointOne() { return (MyGame.PointOneT) value; }
  public MyGame.PointTwoT asPointTwo() { return (MyGame.PointTwoT) value; }

  public static int pack(FlatBufferBuilder builder, PointsUnion _o) {
    switch (_o.type) {
      case Points.PointOne: return MyGame.PointOne.pack(builder, _o.asPointOne());
      case Points.PointTwo: return MyGame.PointTwo.pack(builder, _o.asPointTwo());
      default: return 0;
    }
  }
}

