// automatically generated by the FlatBuffers compiler, do not modify

package union_underlying_type;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class BT {


  public BT() {
  }
}

