# Automatically generated by the FlatBuffers compiler, do not modify.
#
# flatc version: 25.9.23
# Rooting type:  MyGame.Example.Monster ()

require "flatbuffers"

module MyGame
  module Example
    class TypeAliases < ::FlatBuffers::Table
      def i_8
        field_offset = @view.unpack_virtual_offset(4)
        return 0 if field_offset.zero?

        @view.unpack_byte(field_offset)
      end

      def u_8
        field_offset = @view.unpack_virtual_offset(6)
        return 0 if field_offset.zero?

        @view.unpack_ubyte(field_offset)
      end

      def i_16
        field_offset = @view.unpack_virtual_offset(8)
        return 0 if field_offset.zero?

        @view.unpack_short(field_offset)
      end

      def u_16
        field_offset = @view.unpack_virtual_offset(10)
        return 0 if field_offset.zero?

        @view.unpack_ushort(field_offset)
      end

      def i_32
        field_offset = @view.unpack_virtual_offset(12)
        return 0 if field_offset.zero?

        @view.unpack_int(field_offset)
      end

      def u_32
        field_offset = @view.unpack_virtual_offset(14)
        return 0 if field_offset.zero?

        @view.unpack_uint(field_offset)
      end

      def i_64
        field_offset = @view.unpack_virtual_offset(16)
        return 0 if field_offset.zero?

        @view.unpack_long(field_offset)
      end

      def u_64
        field_offset = @view.unpack_virtual_offset(18)
        return 0 if field_offset.zero?

        @view.unpack_ulong(field_offset)
      end

      def f_32
        field_offset = @view.unpack_virtual_offset(20)
        return 0.0 if field_offset.zero?

        @view.unpack_float(field_offset)
      end

      def f_64
        field_offset = @view.unpack_virtual_offset(22)
        return 0.0 if field_offset.zero?

        @view.unpack_double(field_offset)
      end

      def v_8
        field_offset = @view.unpack_virtual_offset(24)
        return nil if field_offset.zero?

        @view.unpack_vector(field_offset, 1) do |element_offset|
          @view.unpack_byte(element_offset)
        end
      end

      def vf_64
        field_offset = @view.unpack_virtual_offset(26)
        return nil if field_offset.zero?

        @view.unpack_vector(field_offset, 8) do |element_offset|
          @view.unpack_double(element_offset)
        end
      end
    end
  end
end
