// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ABC } from './abc.js';
import { EvenMoreStruct, EvenMoreStructT } from './even-more-struct.js';


export class EvenMoreDefaults implements flatbuffers.IUnpackableObject<EvenMoreDefaultsT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos: number = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EvenMoreDefaults {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEvenMoreDefaults(bb:flatbuffers.ByteBuffer, obj?:EvenMoreDefaults):EvenMoreDefaults {
  return (obj || new EvenMoreDefaults()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEvenMoreDefaults(bb:flatbuffers.ByteBuffer, obj?:EvenMoreDefaults):EvenMoreDefaults {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EvenMoreDefaults()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

str(obj?:EvenMoreStruct):EvenMoreStruct|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new EvenMoreStruct()).__init(this.bb_pos + offset, this.bb!) : null;
}

ints(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

intsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

intsArray():Int32Array {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Int32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : new Int32Array();
}

floats(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

floatsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

floatsArray():Float32Array {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : new Float32Array();
}

floatOptional(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

floatOptionalLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

floatOptionalArray():Float32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

bytesOptional(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

bytesOptionalLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

bytesOptionalArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

floatsRequired(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

floatsRequiredLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

floatsRequiredArray():Float32Array {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset));
}

emptyString():string
emptyString(optionalEncoding:flatbuffers.Encoding):string|Uint8Array
emptyString(optionalEncoding?:any):string|Uint8Array {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : "";
}

someString():string
someString(optionalEncoding:flatbuffers.Encoding):string|Uint8Array
someString(optionalEncoding?:any):string|Uint8Array {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : "some";
}

zeroString():string|null
zeroString(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
zeroString(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

aString():string
aString(optionalEncoding:flatbuffers.Encoding):string|Uint8Array
aString(optionalEncoding?:any):string|Uint8Array {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return this.bb!.__string(this.bb_pos + offset, optionalEncoding);
}

requiredString():string
requiredString(optionalEncoding:flatbuffers.Encoding):string|Uint8Array
requiredString(optionalEncoding?:any):string|Uint8Array {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return this.bb!.__string(this.bb_pos + offset, optionalEncoding);
}

abcs(index: number):ABC|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readInt32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : null;
}

abcsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

abcsArray():Int32Array {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? new Int32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : new Int32Array();
}

bools(index: number):boolean|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? !!this.bb!.readInt8(this.bb!.__vector(this.bb_pos + offset) + index) : false;
}

boolsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

boolsArray():Int8Array {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? new Int8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : new Int8Array();
}

oneBool():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

mutate_one_bool(value:boolean):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 30);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt8(this.bb_pos + offset, +value);
  return true;
}

static getFullyQualifiedName(): "EvenMoreDefaults" {
  return 'EvenMoreDefaults';
}

static startEvenMoreDefaults(builder:flatbuffers.Builder):void {
  builder.startObject(14);
}

static addStr(builder:flatbuffers.Builder, strOffset:flatbuffers.Offset):void {
  builder.addFieldStruct(0, strOffset, 0);
}

static addInts(builder:flatbuffers.Builder, intsOffset:flatbuffers.Offset):void {
  builder.addFieldOffset(1, intsOffset, 0);
}

static createIntsVector(builder:flatbuffers.Builder, data:number[]|Int32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createIntsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createIntsVector(builder:flatbuffers.Builder, data:number[]|Int32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startIntsVector(builder:flatbuffers.Builder, numElems:number):void {
  builder.startVector(4, numElems, 4);
}

static addFloats(builder:flatbuffers.Builder, floatsOffset:flatbuffers.Offset):void {
  builder.addFieldOffset(2, floatsOffset, 0);
}

static createFloatsVector(builder:flatbuffers.Builder, data:number[]|Float32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createFloatsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createFloatsVector(builder:flatbuffers.Builder, data:number[]|Float32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addFloat32(data[i]!);
  }
  return builder.endVector();
}

static startFloatsVector(builder:flatbuffers.Builder, numElems:number):void {
  builder.startVector(4, numElems, 4);
}

static addFloatOptional(builder:flatbuffers.Builder, floatOptionalOffset:flatbuffers.Offset):void {
  builder.addFieldOffset(3, floatOptionalOffset, 0);
}

static createFloatOptionalVector(builder:flatbuffers.Builder, data:number[]|Float32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createFloatOptionalVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createFloatOptionalVector(builder:flatbuffers.Builder, data:number[]|Float32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addFloat32(data[i]!);
  }
  return builder.endVector();
}

static startFloatOptionalVector(builder:flatbuffers.Builder, numElems:number):void {
  builder.startVector(4, numElems, 4);
}

static addBytesOptional(builder:flatbuffers.Builder, bytesOptionalOffset:flatbuffers.Offset):void {
  builder.addFieldOffset(4, bytesOptionalOffset, 0);
}

static createBytesOptionalVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startBytesOptionalVector(builder:flatbuffers.Builder, numElems:number):void {
  builder.startVector(1, numElems, 1);
}

static addFloatsRequired(builder:flatbuffers.Builder, floatsRequiredOffset:flatbuffers.Offset):void {
  builder.addFieldOffset(5, floatsRequiredOffset, 0);
}

static createFloatsRequiredVector(builder:flatbuffers.Builder, data:number[]|Float32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createFloatsRequiredVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createFloatsRequiredVector(builder:flatbuffers.Builder, data:number[]|Float32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addFloat32(data[i]!);
  }
  return builder.endVector();
}

static startFloatsRequiredVector(builder:flatbuffers.Builder, numElems:number):void {
  builder.startVector(4, numElems, 4);
}

static addEmptyString(builder:flatbuffers.Builder, emptyStringOffset:flatbuffers.Offset):void {
  builder.addFieldOffset(6, emptyStringOffset, 0);
}

static addSomeString(builder:flatbuffers.Builder, someStringOffset:flatbuffers.Offset):void {
  builder.addFieldOffset(7, someStringOffset, 0);
}

static addZeroString(builder:flatbuffers.Builder, zeroStringOffset:flatbuffers.Offset):void {
  builder.addFieldOffset(8, zeroStringOffset, 0);
}

static addAString(builder:flatbuffers.Builder, aStringOffset:flatbuffers.Offset):void {
  builder.addFieldOffset(9, aStringOffset, 0);
}

static addRequiredString(builder:flatbuffers.Builder, requiredStringOffset:flatbuffers.Offset):void {
  builder.addFieldOffset(10, requiredStringOffset, 0);
}

static addAbcs(builder:flatbuffers.Builder, abcsOffset:flatbuffers.Offset):void {
  builder.addFieldOffset(11, abcsOffset, 0);
}

static createAbcsVector(builder:flatbuffers.Builder, data:ABC[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startAbcsVector(builder:flatbuffers.Builder, numElems:number):void {
  builder.startVector(4, numElems, 4);
}

static addBools(builder:flatbuffers.Builder, boolsOffset:flatbuffers.Offset):void {
  builder.addFieldOffset(12, boolsOffset, 0);
}

static createBoolsVector(builder:flatbuffers.Builder, data:boolean[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(+data[i]!);
  }
  return builder.endVector();
}

static startBoolsVector(builder:flatbuffers.Builder, numElems:number):void {
  builder.startVector(1, numElems, 1);
}

static addOneBool(builder:flatbuffers.Builder, oneBool:boolean):void {
  builder.addFieldInt8(13, +oneBool, +true);
}

static endEvenMoreDefaults(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 14) // floats_required
  builder.requiredField(offset, 22) // a_string
  builder.requiredField(offset, 24) // required_string
  return offset;
}

static createEvenMoreDefaults(builder:flatbuffers.Builder, strOffset:flatbuffers.Offset, intsOffset:flatbuffers.Offset, floatsOffset:flatbuffers.Offset, floatOptionalOffset:flatbuffers.Offset, bytesOptionalOffset:flatbuffers.Offset, floatsRequiredOffset:flatbuffers.Offset, emptyStringOffset:flatbuffers.Offset, someStringOffset:flatbuffers.Offset, zeroStringOffset:flatbuffers.Offset, aStringOffset:flatbuffers.Offset, requiredStringOffset:flatbuffers.Offset, abcsOffset:flatbuffers.Offset, boolsOffset:flatbuffers.Offset, oneBool:boolean):flatbuffers.Offset {
  EvenMoreDefaults.startEvenMoreDefaults(builder);
  EvenMoreDefaults.addStr(builder, strOffset);
  EvenMoreDefaults.addInts(builder, intsOffset);
  EvenMoreDefaults.addFloats(builder, floatsOffset);
  EvenMoreDefaults.addFloatOptional(builder, floatOptionalOffset);
  EvenMoreDefaults.addBytesOptional(builder, bytesOptionalOffset);
  EvenMoreDefaults.addFloatsRequired(builder, floatsRequiredOffset);
  EvenMoreDefaults.addEmptyString(builder, emptyStringOffset);
  EvenMoreDefaults.addSomeString(builder, someStringOffset);
  EvenMoreDefaults.addZeroString(builder, zeroStringOffset);
  EvenMoreDefaults.addAString(builder, aStringOffset);
  EvenMoreDefaults.addRequiredString(builder, requiredStringOffset);
  EvenMoreDefaults.addAbcs(builder, abcsOffset);
  EvenMoreDefaults.addBools(builder, boolsOffset);
  EvenMoreDefaults.addOneBool(builder, oneBool);
  return EvenMoreDefaults.endEvenMoreDefaults(builder);
}

unpack(): EvenMoreDefaultsT {
  return new EvenMoreDefaultsT(
    (this.str() !== null ? this.str()!.unpack() : null),
    this.bb!.createScalarList<number>(this.ints.bind(this), this.intsLength()),
    this.bb!.createScalarList<number>(this.floats.bind(this), this.floatsLength()),
    this.bb!.createScalarList<number>(this.floatOptional.bind(this), this.floatOptionalLength()),
    this.bb!.createScalarList<number>(this.bytesOptional.bind(this), this.bytesOptionalLength()),
    this.bb!.createScalarList<number>(this.floatsRequired.bind(this), this.floatsRequiredLength()),
    this.emptyString(),
    this.someString(),
    this.zeroString(),
    this.aString(),
    this.requiredString(),
    this.bb!.createScalarList<ABC>(this.abcs.bind(this), this.abcsLength()),
    this.bb!.createScalarList<boolean>(this.bools.bind(this), this.boolsLength()),
    this.oneBool()
  );
}


unpackTo(_o: EvenMoreDefaultsT): void {
  _o.str = (this.str() !== null ? this.str()!.unpack() : null);
  _o.ints = this.bb!.createScalarList<number>(this.ints.bind(this), this.intsLength());
  _o.floats = this.bb!.createScalarList<number>(this.floats.bind(this), this.floatsLength());
  _o.floatOptional = this.bb!.createScalarList<number>(this.floatOptional.bind(this), this.floatOptionalLength());
  _o.bytesOptional = this.bb!.createScalarList<number>(this.bytesOptional.bind(this), this.bytesOptionalLength());
  _o.floatsRequired = this.bb!.createScalarList<number>(this.floatsRequired.bind(this), this.floatsRequiredLength());
  _o.emptyString = this.emptyString();
  _o.someString = this.someString();
  _o.zeroString = this.zeroString();
  _o.aString = this.aString();
  _o.requiredString = this.requiredString();
  _o.abcs = this.bb!.createScalarList<ABC>(this.abcs.bind(this), this.abcsLength());
  _o.bools = this.bb!.createScalarList<boolean>(this.bools.bind(this), this.boolsLength());
  _o.oneBool = this.oneBool();
}
}

export class EvenMoreDefaultsT implements flatbuffers.IGeneratedObject {
constructor(
  public str: EvenMoreStructT|null = null,
  public ints: (number)[] = [],
  public floats: (number)[] = [],
  public floatOptional: (number)[] = [],
  public bytesOptional: (number)[] = [],
  public floatsRequired: (number)[] = [],
  public emptyString: string|Uint8Array = "",
  public someString: string|Uint8Array = "some",
  public zeroString: string|Uint8Array|null = null,
  public aString: string|Uint8Array|null = null,
  public requiredString: string|Uint8Array|null = null,
  public abcs: (ABC)[] = [],
  public bools: (boolean)[] = [],
  public oneBool: boolean = true
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const ints = EvenMoreDefaults.createIntsVector(builder, this.ints);
  const floats = EvenMoreDefaults.createFloatsVector(builder, this.floats);
  const floatOptional = EvenMoreDefaults.createFloatOptionalVector(builder, this.floatOptional);
  const bytesOptional = EvenMoreDefaults.createBytesOptionalVector(builder, this.bytesOptional);
  const floatsRequired = EvenMoreDefaults.createFloatsRequiredVector(builder, this.floatsRequired);
  const emptyString = (this.emptyString !== null ? builder.createString(this.emptyString!) : 0);
  const someString = (this.someString !== null ? builder.createString(this.someString!) : 0);
  const zeroString = (this.zeroString !== null ? builder.createString(this.zeroString!) : 0);
  const aString = (this.aString !== null ? builder.createString(this.aString!) : 0);
  const requiredString = (this.requiredString !== null ? builder.createString(this.requiredString!) : 0);
  const abcs = EvenMoreDefaults.createAbcsVector(builder, this.abcs);
  const bools = EvenMoreDefaults.createBoolsVector(builder, this.bools);

  return EvenMoreDefaults.createEvenMoreDefaults(builder,
    (this.str !== null ? this.str!.pack(builder) : 0),
    ints,
    floats,
    floatOptional,
    bytesOptional,
    floatsRequired,
    emptyString,
    someString,
    zeroString,
    aString,
    requiredString,
    abcs,
    bools,
    this.oneBool
  );
}
}
