FROM rust:1.30.1-slim-stretch as base

WORKDIR /setup
RUN apt -qq update >/dev/null
RUN apt -qq install -y curl
RUN curl https://sh.rustup.rs > rustup.sh
RUN cat rustup.sh | sh -s -- -y --default-toolchain none
RUN rustup target add mips-unknown-linux-gnu


WORKDIR /code
ADD . .
WORKDIR /code/tests/rust_usage_test
RUN cargo build --target mips-unknown-linux-gnu
