FROM rust:1.30.1-slim-stretch as base
RUN apt -qq update -y && apt -qq install -y \
    build-essential \
    cmake
WORKDIR /code
ADD . .
RUN cp flatc_debian_stretch flatc
WORKDIR /code/tests
RUN rustc --version
RUN ./RustTest.sh
