FROM hhvm/hhvm:2019.01.16 as base
WORKDIR /code
ADD . .
RUN cp flatc_debian_stretch flatc
WORKDIR /code/tests
RUN hhvm --version
RUN hhvm phpTest.php
RUN ../flatc --php -o php union_vector/union_vector.fbs
RUN hhvm phpUnionVectorTest.php
