// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Example

@Suppress("unused")
class AnyUniqueAliases private constructor() {
    companion object {
        const val NONE: Byte = 0
        const val M: Byte = 1
        const val TS: Byte = 2
        const val M2: Byte = 3
        val names : Array<String> = arrayOf("NONE", "M", "TS", "M2")
        fun name(e: Int) : String = names[e]
    }
}
