from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from MyGame.Example.ArrayStruct import ArrayStruct
from MyGame.Example.NestedStruct import NestedStruct, NestedStructT

class ArrayStruct(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def A(self) -> float: ...
  def B(self, i: int) -> int: ...
  def BAsNumpy(self) -> np.ndarray: ...
  def BLength(self) -> int: ...
  def BIsNone(self) -> bool: ...
  def C(self) -> int: ...
  def D(self, i: int) -> typing.Optional[NestedStruct]: ...
  def DLength(self) -> int: ...
  def DIsNone(self) -> bool: ...
  def E(self) -> int: ...
  def F(self, i: int) -> int: ...
  def FAsNumpy(self) -> np.ndarray: ...
  def FLength(self) -> int: ...
  def FIsNone(self) -> bool: ...
class ArrayStructT(object):
  a: float
  b: typing.List[int]
  c: int
  d: typing.List[NestedStructT]
  e: int
  f: typing.List[int]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ArrayStructT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ArrayStructT: ...
  @classmethod
  def InitFromObj(cls, arrayStruct: ArrayStruct) -> ArrayStructT: ...
  def _UnPack(self, arrayStruct: ArrayStruct) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

