from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class LargeArrayStruct(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def D(self, i: int) -> typing.List[int]: ...
  def DAsNumpy(self) -> np.ndarray: ...
  def DLength(self) -> int: ...
  def DIsNone(self) -> bool: ...
  def E(self, i: int) -> typing.List[float]: ...
  def EAsNumpy(self) -> np.ndarray: ...
  def ELength(self) -> int: ...
  def EIsNone(self) -> bool: ...
  def F(self, i: int) -> typing.List[bool]: ...
  def FAsNumpy(self) -> np.ndarray: ...
  def FLength(self) -> int: ...
  def FIsNone(self) -> bool: ...
class LargeArrayStructT(object):
  d: typing.List[int]
  e: typing.List[float]
  f: typing.List[bool]
  def __init__(
    self,
    d: typing.List[int] | None = ...,
    e: typing.List[float] | None = ...,
    f: typing.List[bool] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> LargeArrayStructT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> LargeArrayStructT: ...
  @classmethod
  def InitFromObj(cls, largeArrayStruct: LargeArrayStruct) -> LargeArrayStructT: ...
  def _UnPack(self, largeArrayStruct: LargeArrayStruct) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

def CreateLargeArrayStruct(builder: flatbuffers.Builder, d: int, e: float, f: bool) -> uoffset: ...

