// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyGame.Example
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LargeArrayStruct : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public LargeArrayStruct __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte D(int j) { return __p.bb.Get(__p.bb_pos + 0 + j * 1); }
  public const int DLength = 64;
#if ENABLE_SPAN_T
  public Span<byte> GetDBytes() { return __p.bb.ToSpan(__p.bb_pos + 0, 64); }
#else
  public ArraySegment<byte>? GetDBytes() { return __p.bb.ToArraySegment(__p.bb_pos + 0, 64);}
#endif
  public void MutateD(int j, byte d) { __p.bb.Put(__p.bb_pos + 0 + j * 1, d); }
  public float E(int j) { return __p.bb.GetFloat(__p.bb_pos + 64 + j * 4); }
  public const int ELength = 64;
#if ENABLE_SPAN_T
  public Span<float> GetEBytes() { return System.Runtime.InteropServices.MemoryMarshal.Cast<byte, float>(__p.bb.ToSpan(__p.bb_pos + 64, 256)); }
#else
  public ArraySegment<byte>? GetEBytes() { return __p.bb.ToArraySegment(__p.bb_pos + 64, 256);}
#endif
  public void MutateE(int j, float e) { __p.bb.PutFloat(__p.bb_pos + 64 + j * 4, e); }
  public bool F(int j) { return 0!=__p.bb.Get(__p.bb_pos + 320 + j * 1); }
  public const int FLength = 64;
#if ENABLE_SPAN_T
  public Span<bool> GetFBytes() { return System.Runtime.InteropServices.MemoryMarshal.Cast<byte, bool>(__p.bb.ToSpan(__p.bb_pos + 320, 64)); }
#else
  public ArraySegment<byte>? GetFBytes() { return __p.bb.ToArraySegment(__p.bb_pos + 320, 64);}
#endif
  public void MutateF(int j, bool f) { __p.bb.Put(__p.bb_pos + 320 + j * 1, (byte)(f ? 1 : 0)); }

  public static Offset<MyGame.Example.LargeArrayStruct> CreateLargeArrayStruct(FlatBufferBuilder builder, byte[] D, float[] E, bool[] F) {
    builder.Prep(4, 384);
    for (int _idx0 = 64; _idx0 > 0; _idx0--) {
      builder.PutBool(F[_idx0-1]);
    }
    for (int _idx0 = 64; _idx0 > 0; _idx0--) {
      builder.PutFloat(E[_idx0-1]);
    }
    for (int _idx0 = 64; _idx0 > 0; _idx0--) {
      builder.PutByte(D[_idx0-1]);
    }
    return new Offset<MyGame.Example.LargeArrayStruct>(builder.Offset);
  }
  public LargeArrayStructT UnPack() {
    var _o = new LargeArrayStructT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(LargeArrayStructT _o) {
    _o.D = new byte[64];
    for (var _j = 0; _j < 64; ++_j) { _o.D[_j] = this.D(_j); }
    _o.E = new float[64];
    for (var _j = 0; _j < 64; ++_j) { _o.E[_j] = this.E(_j); }
    _o.F = new bool[64];
    for (var _j = 0; _j < 64; ++_j) { _o.F[_j] = this.F(_j); }
  }
  public static Offset<MyGame.Example.LargeArrayStruct> Pack(FlatBufferBuilder builder, LargeArrayStructT _o) {
    if (_o == null) return default(Offset<MyGame.Example.LargeArrayStruct>);
    var _d = _o.D;
    var _e = _o.E;
    var _f = _o.F;
    return CreateLargeArrayStruct(
      builder,
      _d,
      _e,
      _f);
  }
}

public class LargeArrayStructT
{
  [Newtonsoft.Json.JsonProperty("d")]
  public byte[] D { get; set; }
  [Newtonsoft.Json.JsonProperty("e")]
  public float[] E { get; set; }
  [Newtonsoft.Json.JsonProperty("f")]
  public bool[] F { get; set; }

  public LargeArrayStructT() {
    this.D = new byte[64];
    this.E = new float[64];
    this.F = new bool[64];
  }
}


}
