from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from MyGame.Example.NestedStruct import NestedStruct

class NestedStruct(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def A(self, i: int) -> int: ...
  def AAsNumpy(self) -> np.ndarray: ...
  def ALength(self) -> int: ...
  def AIsNone(self) -> bool: ...
  def B(self) -> int: ...
  def C(self, i: int) -> int: ...
  def CAsNumpy(self) -> np.ndarray: ...
  def CLength(self) -> int: ...
  def CIsNone(self) -> bool: ...
  def D(self, i: int) -> int: ...
  def DAsNumpy(self) -> np.ndarray: ...
  def DLength(self) -> int: ...
  def DIsNone(self) -> bool: ...
class NestedStructT(object):
  a: typing.List[int]
  b: int
  c: typing.List[int]
  d: typing.List[int]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> NestedStructT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> NestedStructT: ...
  @classmethod
  def InitFromObj(cls, nestedStruct: NestedStruct) -> NestedStructT: ...
  def _UnPack(self, nestedStruct: NestedStruct) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

