# automatically generated by the FlatBuffers compiler, do not modify

# module: Example

import FlatBuffers

FlatBuffers.@with_kw mutable struct Referrable
    id::UInt64 = 0
end
FlatBuffers.@ALIGN(Referrable, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T<:Referrable} = [
    0x00000004
]

Referrable(buf::AbstractVector{UInt8}) = FlatBuffers.read(Referrable, buf)
Referrable(io::IO) = FlatBuffers.deserialize(io, Referrable)
