from __future__ import annotations

import flatbuffers
import numpy as np

from MyGame.Example.Referrable import Referrable

class Referrable(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Referrable: ...
  @classmethod
  def GetRootAsReferrable(cls, buf: bytes, offset: int) -> Referrable: ...
  @classmethod
  def ReferrableBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> int: ...
class ReferrableT(object):
  id: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ReferrableT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ReferrableT: ...
  @classmethod
  def InitFromObj(cls, referrable: Referrable) -> ReferrableT: ...
  def _UnPack(self, referrable: Referrable) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

