// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Example

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
@ExperimentalUnsignedTypes
class StringKey : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : StringKey {
        __init(_i, _bb)
        return this
    }
    val k : String?
        get() {
            val o = __offset(4)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val kAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun kInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    override fun keysCompare(o1: Int, o2: Int, _bb: ByteBuffer) : Int {
         return compareStrings(__offset(4, o1, _bb), __offset(4, o2, _bb), _bb)
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_1_12_0()
        fun getRootAsStringKey(_bb: ByteBuffer): StringKey = getRootAsStringKey(_bb, StringKey())
        fun getRootAsStringKey(_bb: ByteBuffer, obj: StringKey): StringKey {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createStringKey(builder: FlatBufferBuilder, kOffset: Int) : Int {
            builder.startTable(1)
            addK(builder, kOffset)
            return endStringKey(builder)
        }
        fun startStringKey(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addK(builder: FlatBufferBuilder, k: Int) = builder.addOffset(0, k, 0)
        fun endStringKey(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
            return o
        }
        fun __lookup_by_key(obj: StringKey?, vectorLocation: Int, key: String, bb: ByteBuffer) : StringKey? {
            val byteKey = key.toByteArray(java.nio.charset.StandardCharsets.UTF_8)
            var span = bb.getInt(vectorLocation - 4)
            var start = 0
            while (span != 0) {
                var middle = span / 2
                val tableOffset = __indirect(vectorLocation + 4 * (start + middle), bb)
                val comp = compareStrings(__offset(4, bb.capacity() - tableOffset, bb), byteKey, bb)
                when {
                    comp > 0 -> span = middle
                    comp < 0 -> {
                        middle++
                        start += middle
                        span -= middle
                    }
                    else -> {
                        return (obj ?: StringKey()).__assign(tableOffset, bb)
                    }
                }
            }
            return null
        }
    }
}
