# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
permissions: read-all

on: [pull_request_target]

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@ee18d5d34efd9b4f7dafdb0e363cb688eb438044 # 4.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
